### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by vmalloc** [getslash/backslash#459]
This issue will be the focal point to current performance issues. Our main problem at the moment are bursts of requests from parallel sessions, which cause long queues on gunicorn (still under investigation).

To Investigate:
- [x] Queue lengths during peak load (partly addressed by #457)
- [x] Can certain requests on the critical path be optimized?

To do:
- [x] Benchmark tool (#458)
- [x] Timing headers (#460)
- [x] Use timing headers in API server measurements (#461)
- [x] Separate UI backend from API backend to avoid UI starvation (#466)
